import { NeighborComment, SentimentType, CommentTag, CommentStatus } from '@shared/types/comments'

export const sampleComments: NeighborComment[] = [
  {
    id: '1',
    applicationId: 'APP-001',
    name: 'Sarah',
    surname: 'Johnson',
    email: 'sarah.johnson@email.com',
    neighborAddress: '123 Main Street, Springfield, IL 62701',
    coordinates: { latitude: 39.7817, longitude: -89.6501 },
    content: 'I have concerns about the increased traffic this development will bring to our quiet residential street. The proposed design also seems out of character with the existing neighborhood architecture.',
    sentiment: 'negative' as SentimentType,
    tags: ['Traffic', 'Design'] as CommentTag[],
    submissionDate: new Date('2024-01-15'),
    status: 'pending_review' as CommentStatus,
    isRedacted: false,
    officerNotes: 'Valid concerns raised about traffic impact',
    isEdited: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15')
  },
  {
    id: '2',
    applicationId: 'APP-001',
    name: 'Michael',
    surname: 'Chen',
    email: 'michael.chen@email.com',
    neighborAddress: '456 Oak Avenue, Springfield, IL 62702',
    coordinates: { latitude: 39.7901, longitude: -89.6445 },
    content: 'This development looks great and will bring much-needed housing to our area. I appreciate that the developers have included green spaces and considered accessibility in their design.',
    sentiment: 'positive' as SentimentType,
    tags: ['Use', 'Design', 'Access'] as CommentTag[],
    submissionDate: new Date('2024-01-18'),
    status: 'approved_for_publication' as CommentStatus,
    isRedacted: false,
    isEdited: false,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18')
  },
  {
    id: '3',
    applicationId: 'APP-001',
    name: 'Emily',
    surname: 'Rodriguez',
    email: 'emily.rodriguez@email.com',
    neighborAddress: '789 Pine Street, Springfield, IL 62703',
    coordinates: { latitude: 39.7952, longitude: -89.6532 },
    content: 'My main concern is about privacy. The proposed building height will allow residents to look directly into my backyard and home. Additionally, I am worried about noise levels during construction and after occupancy.',
    sentiment: 'negative' as SentimentType,
    tags: ['Privacy', 'Noise'] as CommentTag[],
    submissionDate: new Date('2024-01-20'),
    status: 'redacted' as CommentStatus,
    isRedacted: true,
    officerNotes: 'Contains specific personal details that need redaction',
    isEdited: true,
    originalContent: 'My main concern is about privacy. The proposed building height will allow residents to look directly into my backyard at [PERSONAL ADDRESS] and home. Additionally, I am worried about noise levels during construction and after occupancy.',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-22')
  },
  {
    id: '4',
    applicationId: 'APP-001',
    name: 'David',
    surname: 'Wilson',
    email: 'david.wilson@email.com',
    neighborAddress: '321 Elm Drive, Springfield, IL 62704',
    coordinates: { latitude: 39.7889, longitude: -89.6423 },
    content: 'I think this project has potential but I have concerns about lighting. Will there be adequate street lighting for safety? Also, how will this affect access to the community park nearby?',
    sentiment: 'neutral' as SentimentType,
    tags: ['Light', 'Access'] as CommentTag[],
    submissionDate: new Date('2024-01-22'),
    status: 'pending_review' as CommentStatus,
    isRedacted: false,
    isEdited: false,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22')
  },
  {
    id: '5',
    applicationId: 'APP-001',
    name: 'Lisa',
    surname: 'Thompson',
    email: 'lisa.thompson@email.com',
    neighborAddress: '654 Maple Court, Springfield, IL 62705',
    coordinates: { latitude: 39.7834, longitude: -89.6487 },
    content: 'I have several concerns that do not fit into typical categories. The environmental impact study seems incomplete, and I am worried about the long-term effects on local wildlife. The drainage plans also appear insufficient.',
    sentiment: 'negative' as SentimentType,
    tags: ['Other'] as CommentTag[],
    submissionDate: new Date('2024-01-25'),
    status: 'pending_review' as CommentStatus,
    isRedacted: false,
    isEdited: false,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25')
  }
]